version: '2.2'
services:
  php:
    container_name: php
#    image: php:7.4.27-fpm-alpine3.15
    build: ./images/php
    restart: always
    volumes:
      - /rpool/data/subvol-235-disk-0/var/www/clients/client0/web1/web:/var/www/popusti.rs/web
      - /rpool/data/subvol-235-disk-0/var/www/clients/client0/web1:/var/www/clients/client0/web1
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    user: "105004:105005"
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.21.5-alpine
    ports:
      - 185.125.56.234:80:80
    volumes:
      - /rpool/data/subvol-235-disk-0/var/www/clients/client0/web1/web:/var/www/popusti.rs/web
      - ./nginx/popusti.rs.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/robots.txt:/var/www/popusti.rs/web/robots.txt
    depends_on:
      - php
